### ISSUE TITLE
How to change the size of bars in column chart ?

### ISSUE THREAD

**Issue by khmaies5** [patrykandpatryk/vico#76]
First of all nice work guys on this lib, its beautiful.

i am trying to implement this lib in a project and i have to make the bars larger and remove the guidelines from the bg but i couldn't find a way to do this

**Comment by Gowsky** [comment]
Hi @khmaies5!

You can define the columns’ (bars’) thickness right in `LineComponent`’s [constructor](https://vico.patrykandpatryk.com/vico/core/com.patrykandpatryk.vico.core.component.shape/-line-component/-line-component). Alternatively you can use [`lineComponent()`](https://vico.patrykandpatryk.com/vico/compose/com.patrykandpatryk.vico.compose.component/line-component?query=fun%20lineComponent(color:%20Color%20=%20Color.Black,%20thickness:%20Dp%20=%20DefaultDimens.COLUMN_WIDTH.dp,%20shape:%20Shape%20=%20RectangleShape,%20dynamicShader:%20DynamicShader?%20=%20null,%20margins:%20Dimensions%20=%20emptyDimensions(),%20strokeWidth:%20Dp%20=%200.dp,%20strokeColor:%20Color%20=%20Color.Transparent):%20LineComponent) function if you are using Jetpack Compose.

In order to hide the guidelines, you need to set `guideline` to `null` while creating an axis.
You can use a [horizontal axis builder](https://vico.patrykandpatryk.com/vico/core/com.patrykandpatryk.vico.core.axis.horizontal/create-horizontal-axis?query=inline%20fun%20%3CPosition%20:%20AxisPosition.Horizontal%3E%20createHorizontalAxis(block:%20HorizontalAxis.Builder%3CPosition%3E.()%20-%3E%20Unit%20=%20{}):%20HorizontalAxis%3CPosition%3E), or [vertical axis builder](https://vico.patrykandpatryk.com/vico/core/com.patrykandpatryk.vico.core.axis.vertical/create-vertical-axis?query=inline%20fun%20%3CPosition%20:%20AxisPosition.Vertical%3E%20createVerticalAxis(block:%20VerticalAxis.Builder%3CPosition%3E.()%20-%3E%20Unit%20=%20{}):%20VerticalAxis%3CPosition%3E). There's also compose-only functions such as [startAxis()](https://vico.patrykandpatryk.com/vico/compose/com.patrykandpatryk.vico.compose.axis.vertical/start-axis) etc.

**Comment by khmaies5** [comment]
I will check it out, also I am not using compose.
I believe that this lib has a lot of potential but it's not well documented or have enough examples on how to use it in different scenarios (i am talking about not so advanced developers)

**Comment by khmaies5** [comment]
> Hi @khmaies5!
> 
> You can define the columns’ (bars’) thickness right in `LineComponent`’s [constructor](https://vico.patrykandpatryk.com/vico/core/com.patrykandpatryk.vico.core.component.shape/-line-component/-line-component). Alternatively you can use [`lineComponent()`](https://vico.patrykandpatryk.com/vico/compose/com.patrykandpatryk.vico.compose.component/line-component?query=fun%20lineComponent(color:%20Color%20=%20Color.Black,%20thickness:%20Dp%20=%20DefaultDimens.COLUMN_WIDTH.dp,%20shape:%20Shape%20=%20RectangleShape,%20dynamicShader:%20DynamicShader?%20=%20null,%20margins:%20Dimensions%20=%20emptyDimensions(),%20strokeWidth:%20Dp%20=%200.dp,%20strokeColor:%20Color%20=%20Color.Transparent):%20LineComponent) function if you are using Jetpack Compose.
> 
> In order to hide the guidelines, you need to set `guideline` to `null` while creating an axis. You can use a [horizontal axis builder](https://vico.patrykandpatryk.com/vico/core/com.patrykandpatryk.vico.core.axis.horizontal/create-horizontal-axis?query=inline%20fun%20%3CPosition%20:%20AxisPosition.Horizontal%3E%20createHorizontalAxis(block:%20HorizontalAxis.Builder%3CPosition%3E.()%20-%3E%20Unit%20=%20%7B%7D):%20HorizontalAxis%3CPosition%3E), or [vertical axis builder](https://vico.patrykandpatryk.com/vico/core/com.patrykandpatryk.vico.core.axis.vertical/create-vertical-axis?query=inline%20fun%20%3CPosition%20:%20AxisPosition.Vertical%3E%20createVerticalAxis(block:%20VerticalAxis.Builder%3CPosition%3E.()%20-%3E%20Unit%20=%20%7B%7D):%20VerticalAxis%3CPosition%3E). There's also compose-only functions such as [startAxis()](https://vico.patrykandpatryk.com/vico/compose/com.patrykandpatryk.vico.compose.axis.vertical/start-axis) etc.

I changed the thickness and hid the guideline using styling but that messedup the view so i tried to do what you told me but i wasn't successful.
I am using the sample app.

one other reauest, can we edit the y&x axis steps? for example i want the x axis to count from 0 to 10 and step by 5 so it shows 0->5->10 and the y axis to show 24h format from 00:00 -> 08:00 -> 16:00 -> 00:00

**Comment by patrykmichalik** [comment]
Hello! Hereʼs a quick example. I hope it helps.

```xml
<com.patrykandpatryk.vico.view.chart.ChartView
    android:id="@+id/chart"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:showBottomAxis="true"
    app:showStartAxis="true" />
```

```kt
with (binding.chart) {
    setModel(
        model = entryModelOf(
            0f to 10f,
            5f to 15f,
            10f to 20f,
        ),
    )
    chart = ColumnChart(
        column = LineComponent(
            thicknessDp = 24f,
            color = Color.BLACK,
        ),
    )
    (startAxis as Axis).guideline = null
    with (bottomAxis as Axis) {
        guideline = null
        valueFormatter = AxisValueFormatter { _, _ -> "Test" }
    }
}
```

![image](https://user-images.githubusercontent.com/56888459/168018354-d9868eb9-11f5-4775-a45f-23e3855768f2.png)

**Comment by khmaies5** [comment]
Thank you, this is really helpful

**Comment by Gowsky** [comment]
I assume that this issue can be closed now.
