### ISSUE TITLE
Axis label size

### ISSUE THREAD

**Issue by TheDome0** [patrykandpatryk/vico#82]
Is there any way to modify the size of `axisLabelComponent`?

As shown in the picture it cuts the text off, `sizeConstraint` does not have any impact on the label.
Padding/margin is all 0, `ellipsize` is set to `TruncateAt.END`.
![image](https://user-images.githubusercontent.com/85122272/168906180-b7ad1f44-f3b7-4d8d-a8f9-2ca15f882a86.png)
The second picture uses `TruncateAt.MARQUEE` as a workaround
![image](https://user-images.githubusercontent.com/85122272/168906196-8c85e501-48c0-473e-8a7f-ef287b4174fa.png)

**Comment by patrykmichalik** [comment]
Hello! The size of axis labels is limited horizontally so that they don’t stick out past the edges of corresponding chart segment:

![Group 33](https://user-images.githubusercontent.com/56888459/169243058-9d930313-9ff0-435e-bad3-a39d195a5984.png)

In order to ensure that longer labels fit, you’d have to make the chart segments wider (for example, if you’re working with a column chart, by making the columns wider). It’s also worth noting that you can create multi-line labels. Some further notes:

- For horizontal axes, `SizeConstraint` controls the height of the axis. This can impact axis labels, but in your case, the truncation is occurring due to insufficient horizontal space.

- There is a bug in Vico 1.0.0 Alpha 3 that may cause rotated axis labels to be incorrectly truncated. This will be fixed with the next update. However, in your case, the bug doesn’t affect the way axis labels are drawn.
